Add wf call

diff --git a/.github/workflows/workflow-dev.yml b/.github/workflows/workflow-dev.yml
--- a/.github/workflows/workflow-dev.yml
+++ b/.github/workflows/workflow-dev.yml
@@ -4,6 +4,13 @@ on:
   push:
     branches:
       - main
+  workflow_call:
+    inputs:
+      service_name:
+        description: "Name of the service to deploy"
+        required: true
+        type: string
+        default: ${{ github.event.repository.name }}
 
 jobs:
   build:
@@ -12,7 +19,8 @@ jobs:
       - uses: actions/checkout@v4
       - name: Build image locally
         run: |
-          docker build -t ${{ github.event.repository.name }}:latest .
+          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
+          docker build -t $SERVICE_NAME:latest .
 
   deploy_local:
     needs: build
@@ -30,4 +38,5 @@ jobs:
 
       - name: Deploy local stack
         run: |
-          docker stack deploy -c docker-compose.yaml ${{ github.event.repository.name }} || { echo "Deployment failed"; exit 1; }
+          SERVICE_NAME=${{ inputs.service_name || github.event.repository.name }}
+          docker stack deploy -c docker-compose.yaml $SERVICE_NAME || { echo "Deployment failed"; exit 1; }
